### ISSUE TITLE
As a user, I want login so that I can access my profile

### ISSUE THREAD

**Issue by 0x91CEA55** [tatumalenko/CourseBin#10]
**User Story**

- [x] #43 (Login error message)

- [x] #44 (on success route)

- [x] #49 (clear input fields on enter key press)

- [x] #53 (Navbar Alignment)

**Acceptance Criteria**

**Definition of Done**
