### ISSUE TITLE
As a user, I want to let algorithms compute an optimal schedule given my restrictions

### ISSUE THREAD

**Issue by JeremiahTee** [tatumalenko/CourseBin#31]
**User Story**

**Acceptance Criteria**

**Definition of Done**

**TODO**
- [x] Take into account courses that are never offered in some terms for `ProgramBuilder.findCandidateSequences` method @tatumalenko 
- [x] Take into account special cases like SOEN490 that span 2 terms for both `ProgramBuilder.findCandidateSequences` and `ProgramBuilder.findCandidateSchedules` methods @tatumalenko 
- [x] Look into stupid issue with `Array[TimeBlock]` (2+) because of the parsing where I say if `'weekDay' !== 'N'`, for many `'THURSDAY'` keys, the value is null for no apparent reason (grr) @tatumalenko 
- [x] Look into Student collection and mapping it to a logged in User by having an id associated to each User @tatumalenko 
- [x] Implement `Plan.findCandidatePlan` tests for every case needed for demo 
- [x] Implement `Plan.sortSchedules` method @jaychenblue 
- [x] Implement `Plan.sortSchedules` tests @jaychenblue 
- [x] Implement `Util.timesOverlap` method @r-saba 
- [x] Implement `Util.timesOverlap` tests @r-saba 
- [x] Add course Name in Section object (i.e Object Oriented Programming I)@tatumalenko 
- [x] Change section to courses (in sequences) @tatumalenko 
- [x] Add year to  sequence object @tatumalenko 
- [x] Return course object in Sequence object instead of a String array @tatumalenko
